version: "3.7"

services:
  zk:
    container_name: zk
    image: zookeeper:3.4
    ports:
      - "2181:2181"
      - "3888:3888"
      - "2888:2888"

  ch1:
    container_name: ch1
    image: yandex/clickhouse-server:20.1
    ports:
      # http_port
      - "8123:8123"
      # tcp_port
      - "9000:9000"
      # https_port
      #- "8443:8443"
      # tcp_port_secure
      #- "9440:9440"
      # interserver_http_port
      - "9009:9009"
      # mysql_port
      - "9004:9004"
    volumes:
      - "./ch1:/var/lib/clickhouse"
      - ./config.d:/etc/clickhouse-server/config.d"
      - ./metrica_ch1.xml:/etc/metrica.xml"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  ch2:
    container_name: ch2
    image: yandex/clickhouse-server:20.1
    ports:
      # http_port
      - "8223:8123"
      # tcp_port
      - "9200:9000"
      # https_port
      #- "8443:8443"
      # tcp_port_secure
      #- "9440:9440"
      # interserver_http_port
      - "9209:9009"
      # mysql_port
      - "9204:9004"
    volumes:
      - "./ch2:/var/lib/clickhouse"
      - ./config.d:/etc/clickhouse-server/config.d"
      - ./metrica_ch2.xml:/etc/metrica.xml"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
